name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Your GitHub user name
          user: Mayzero
          # Path/filename to use to store generated SVG
          filename: github-metrics.svg
          plugin_pagespeed: no
          
          plugin_isocalendar: yes
          
          plugin_languages: yes
